version: "2"
services:
  worker:
    # replace username/repo:tag with your name and image details
    image: ubuntu:latest
    command: bash
    # command: bash /source/init.sh
    volumes: 
      - ./:/source      
      # - ./rnn-text-classification-tf:/rnn-text-classification-tf
    # ports:
    #  - "1506:1506"
    # restart: always
    tty: true
    